version: '3.8'

services:
  # Todo List Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MYSQL_PUBLIC_URL=mysql://root:UZXvQgetqzklDuinMGdWkpHiOHUoZESF@gondola.proxy.rlwy.net:12442/railway
      - DB_HOST=gondola.proxy.rlwy.net
      - DB_PORT=12442
      - DB_USER=root
      - DB_PASSWORD=UZXvQgetqzklDuinMGdWkpHiOHUoZESF
      - DB_NAME=railway
      - DB_SSL=true
    restart: unless-stopped
    networks:
      - todo-network

  # MySQL Database  
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todolist
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network
    restart: unless-stopped

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
